# Generated by Django 3.0.5 on 2020-12-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0007_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(choices=[('Immediate attention', 'Immediate attention'), ('financial crisis', 'financial crisis'), ('Chaos b/w people', 'Chaos b/w people'), ('Natural disater', 'Natural disater')], max_length=50),
        ),
    ]
